/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function reflinkFile(src: string, dst: string): Promise<number>
export function reflinkFileSync(src: string, dst: string): number
