/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function reflinkFile(src: string, dst: string): Promise<number>
export declare function reflinkFileSync(src: string, dst: string): number
